version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      opengemini:
        condition: service_healthy
      extension:
        condition: service_started
    volumes:
      - type: volume
        source: cache
        target: /var/data
    links:
      - opengemini
  extension:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - "GO_BUILDER=ghcr.io/linuxsuren/library/golang:1.22"
        - "BASE_IMAGE=ghcr.io/linuxsuren/library/alpine:3.12"
        - GOPROXY=${GOPROXY}

  opengemini:
    image: ghcr.io/linuxsuren/opengeminidb/opengemini-server:1.2.0
    environment:
      opengemini_USER: root
      opengemini_PASSWORD: root
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8086"]
      interval: 3s
      timeout: 30s
      retries: 30
    ports:
      - 9042
volumes:
  cache:
